[project]
name = "radiomesh"
version = "0.1.0"
description = "Just a basic numba gridder"
authors = [
    {name = "landmanbester", email = "lbester@sarao.ac.za"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "pytest>=8.0.0",
    "numpy>=2.0.0",
    "numba>=0.60.0",
    "sympy>=1.9",
    "scipy"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
